
name: samosa_workflow
on: push
jobs:
  upload1:
    name: uploading office files to server
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          echo "Samosa is very tasty"
          echo "samosa is not health"          
  job2:
    uses: org-Santhosh/reusable/.github/workflows/called.yml@main
