
name: samosa_workflow
on: push
jobs:
  upload1:
    name: uploading office files to server
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        if: github.event.ref == 'refs/heads/branch_test2_prauto'
        run: |
          echo $GITHUB_REF
