name: CI_CD_WORKFLOW   

on:
  workflow_dispatch:
  push:
    branches: 
      - branch**
      - develop

  pull_request:
    branches:
     - develop
     
jobs:
  collecting-logs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2 
      
    #GET /repos/{owner}/{repo}/actions/jobs/{job_id}
    # https://api.github.com/repos/octocat/hello-world/actions/jobs/42/logs

    - name: downloading logs from github actions
      run: | 
        ls
        echo ${{ github.run_id }} 
        echo ${{ github.workflow }}
        echo ${{ github.workflow_id }}
        echo $GITHUB_JOB
        echo $GITHUB_JOB_ID
        echo $GITHUB_RUN_ID
        echo $GITHUB_RUN_NUMBER	
        echo "------------------------------------- curling "
        GITHUB_CHECK_SUITE_ID=`curl -s https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID} | jq -r '.check_suite_id'`
        #curl -sSf -H "authToken: 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" -O 'https://github.com/org-Santhosh/reusable/suites/$GITHUB_CHECK_SUITE_ID/logs'
        #curl -H "Accept: application/vnd.github.v3.diff" https://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:x-oauth-basic@api.github.com/repos/<org>/<repo>/pulls/<pull request>
        curl -u san39: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 -H 'Accept: application/vnd.github.v3.raw' -O -L  "https://github.com/org-Santhosh/reusable/suites/$GITHUB_CHECK_SUITE_ID/logs"
        
        echo $GITHUB_CHECK_SUITE_ID
        #wget https://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@github.com/org-Santhosh/reusable/suites/$GITHUB_CHECK_SUITE_ID/logs
        #curl -v -u username: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  https://github.com/org-Santhosh/reusable/suites/$GITHUB_CHECK_SUITE_ID/logs
        #curl -H 'authToken: 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' https://github.com/org-Santhosh/reusable/suites/$GITHUB_CHECK_SUITE_ID/logs
        
        echo "--------------------------------------------"
        #curl  https://api.github.com/repos/org-Santhosh/reusable/actions/runs/$GITHUB_RUN_ID/jobs
        echo "----------------------"
        #curl -v -u username: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 -H "Accept: application/vnd.github.v3+json" https://github.com/philips-internal/ampm-cicd-reference-application/actions/runs/$GITHUB_RUN_ID/logs
        #curl -v -u username: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 -H "Accept: application/vnd.github.v3+json" https://github.com/org-Santhosh/reusable/suites/$GITHUB_CHECK_SUITE_ID/logs
        #wget https://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@github.com/org-Santhosh/reusable/suites/$GITHUB_CHECK_SUITE_ID/logs
        echo "--------------------------------------"
        #curl -v -u username:${{ secrets.AM_ELK }} -H "Accept: application/vnd.github.v3+json" https://github.com/philips-internal/ampm-cicd-reference-application/actions/runs/5981141428/logs
        #wget https://${{ secrets.AM_ELK }}@github.com/philips-internal/ampm-cicd-reference-application/actions/runs/5981141428/logs
        ls
        #cd logs
        pwd
     
    - uses: actions/upload-artifact@v3
      with:
        name: logs
        path: logs
        
    #- name: using github cli  
    #  run: |
    #    gh --version
    #    sudo echo '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' > mytoken.txt
    #    ls
    #    gh auth login --help
    #    sudo gh auth login --with-token < mytoken.txt
    #    sudo gh run view $GITHUB_RUN_ID --log

        
        
  collecting-logs2:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2 
