
name: samosa_workflow
on: push
jobs:
  upload1:
    name: uploading office files to server
    runs-on: ubuntu-latest
    steps:
      - name: python
        id: check
        shell: python
        run: |
          arr = ['use_sonarqube']
          use_sonar = 'use_sonarqube'
          a = if(use_sonar in arr): 
          print(a)
          print("::set-output name=checkk::f")
        
      - id: date
        run: |
          echo "::set-output name=date::failure"
          echo ${{ steps.check.outputs.checkk }}
          
          
      - name: test
        if: ${{ steps.date.outputs.date == 'failure' }}
        run: |
          echo "santhosh"
          echo ${{ steps.date.outputs.date }}
 
