
name: new
on: push
jobs:
  upload1:
    name: uploading office files to server
    runs-on: ubuntu-latest
    environment: test
    steps:
    
      - name:  Checkout Repository from GitHub      
        uses: actions/checkout@v2
        
      - name: test
        #if : {{ $environment == test1 }}
        run: |
          echo ${{ environment }} == QA Space
