
name: samosa_workflow
on: push
jobs:
  upload1:
    name: uploading office files to server
    runs-on: ubuntu-latest
    steps:
      - name: python
        id: check
        shell: python
        run: |
          arr = ['use_sonarqube']
          use_sonar = 'use_sonarqube'
          print "::set-output name=check::failure"
        
      - id: date
        run: |
          echo "::set-output name=date::failure"
          echo ${{ steps.python.outputs.check }}
          
          
      - name: test
        if: ${{ steps.date.outputs.date == 'failure' }}
        run: |
          echo "santhosh"
          echo ${{ steps.date.outputs.date }}
 
