
name: samosa_workflow
on: push
jobs:
  upload1:
    name: uploading office files to server
    runs-on: ubuntu-latest
    steps:
      - name: python
        id: check
        shell: python
        run: |
          arr = ['use_sonarqube']
          use_sonar = 'use_sonarqube'
          if(use_sonar in arr):
            print("::set-output name=checkk::true")
        
      - id: date
        run: |
          #echo "::set-output name=date::true"
          echo ${{ steps.check.outputs.checkk }}
          
          
      - name: test
        if: ${{ steps.check.outputs.checkk == true }}
        run: |
          echo "santhosh"
          echo ${{ steps.date.outputs.date }}
 
