name: caller
on: push
jobs:
  job1:
    runner: ubuntu-latest
    steps:
      -name: step1
       run: |
         echo "line1"
         
  job2:
    uses: org-Santhosh/reusable/.github/workflows/called.yml@main
