name: CI_CD_WORKFLOW  

on:
  workflow_dispatch:
  push:
    branches: 
      - branch**
      - develop

  pull_request:
    branches:
     - develop
     
jobs:
  collecting-logs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2 
      
    #GET /repos/{owner}/{repo}/actions/jobs/{job_id}
    # https://api.github.com/repos/octocat/hello-world/actions/jobs/42/logs

    - name: downloading logs from github actions
      run: | 
        ls
        echo ${{ github.run_id }} 
        echo ${{ github.workflow }}
        echo ${{ github.workflow_id }}
        echo $GITHUB_JOB
        echo $GITHUB_JOB_ID
        echo $GITHUB_RUN_ID
        echo $GITHUB_RUN_NUMBER	
        echo "-------------------------------------"
        curl  https://api.github.com/repos/org-Santhosh/reusable/actions/runs/$GITHUB_RUN_ID/jobs
        echo "--------------------------------------"
        #curl -v -u username:${{ secrets.AM_ELK }} -H "Accept: application/vnd.github.v3+json" https://github.com/philips-internal/ampm-cicd-reference-application/actions/runs/5981141428/logs
        #wget https://${{ secrets.AM_ELK }}@github.com/philips-internal/ampm-cicd-reference-application/actions/runs/5981141428/logs
        ls
  collecting-logs2:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2 
