
name: samosa_workflow
on: push
jobs:
  upload1:
    name: uploading office files to server
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Checkout Repository from GitHub
        uses: actions/checkout@v2
        
      - name: checking docker
        run: |
          docker --version
      
      - name: checking files
        run: |
          docker images
          ls
