
name: new
on: push
jobs:
  upload1:
    name: uploading office files to server
    runs-on: ubuntu-latest
    steps:
    
      - name:  Checkout Repository from GitHub      
        uses: actions/checkout@v2
        
      - shell: bash
        if: github.event.ref == 'refs/heads/branch_test2_prauto'
        run: |
          echo $GITHUB_REF
          cd san/thosh
          ls
          
      - name: upload- 
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: san
          
      - name: test
        run: ls
