
name: samosa_workflow
on: push
jobs:
  upload1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Checkout Repository from GitHub
        uses: actions/checkout@v2
        
      - shell: bash
        run: |
          ls
          pwd
          sudo curl -XPOST http://35.89.33.99:9200/_bulk?pretty --data-binary @Worker_20220404-135348-utc.log -H "Content-Type: application/json"

      - uses: actions/upload-artifact@v3
        with:
          name: logs
          path: /home/runner/runners/2.289.1/_diag
          
