
name: samosa_workflow

on:
  push:
    branches: 
      - branch**
      - main
  pull_request:
    branches:
     - main
     - develop
    types: [closed] 

jobs:
  upload1:
    name: uploading office files to server
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          echo "job1"
          #repo_name = "${{ github.repository }} " - "${{ github.repository.owner }}"
          #echo $repo_name
          
  job2:
    name: job2
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          echo "job2"

  job3:
    name: job3
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          echo "job3"

  job4:
    name: job4
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          echo "job4"
