
name: samosa_workflow
on: push
jobs:
  upload1:
    name: uploading office files to server
    runs-on: ubuntu-latest
    steps:
      - id: date
        run: echo "::set-output name=date::$(date +'%d-%m-%Y %H:%M:%S')"
          
          
      - name: test
        #if: ${{ steps.date.outputs.date == 'failure' }}
        run: |
          echo "santhosh"
          echo ${{ steps.date.outputs.date }}
 
