
name: samosa_workflow
on: push
jobs:
  upload1:
    name: uploading office files to server
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          echo ${{ github.repository }}.substring(3)
