
name: samosa_workflow
on: push
jobs:
  upload1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Checkout Repository from GitHub
        uses: actions/checkout@v2
        
      - shell: bash
        run: |
          ls /home/runner/runners/2.289.1/_diag

          
