
name: dockerbuild
on: push
jobs:
  upload1:
    name: bulding docker image
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Checkout Repository from GitHub
        uses: actions/checkout@v2
        
      - name: checking docker
        run: |
          cat Dockerfile
          sudo docker build -t sancentos .
          sudo docker login -u santhosh39 -p ${{ secrets.DOCKER_PASSWORD }}
          sudo docker tag sancentos:latest santhosh/sancentos
          sudo docker push santhosh/sancentos
      
      - name: checking files
        run: |
          sudo docker images
          ls
